### ISSUE TITLE
Build fails on macOS Big Sur and SDK 12.4

### ISSUE THREAD

**Issue by ahmedalalousi** [tpoechtrager/osxcross#257] opened 2021-02-08 19:47 UTC
Folks,

Hard as I tried, this build simply fails; summary is that ./build.sh returns (partial dump):

extract.c:121:4: error: implicit declaration of function 'warn' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        warn("%s", file);
                        ^
extract.c:135:4: error: implicit declaration of function 'warn' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        warn("chmod: %s", file);
                        ^
extract.c:141:5: error: implicit declaration of function 'warn' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                                warn("utimes: %s", file);

Has anyone actually built osxcross on Big Sur? any pointers?

Thanks.

**Comment by Gcenx** [comment] 2021-03-17 17:45
Xcode12 now by default adds `-Werror,-Wimplicit-function-declaration`

Use the following CFLAGS to disable the behavior and you’ll be all set.
```
CFLAGS=-Wno-implicit-function-declaration
```

**Comment by tpoechtrager** [comment] 2021-03-20 14:55
I can't reproduce this error with the 12.5 Beta 3 SDK. `warn()` is declared in the `err.h` header file which ships with the SDK. So it must be the SDK that's broken.

**Comment by Gcenx** [comment] 2021-03-20 15:04
Does this happen with stock Xcode12.4 or command line tools?

It’s possible Apple only fixed there own SDK in the Xcode 12.5 Beta3

**Comment by tpoechtrager** [comment] 2021-03-22 17:20
I have tried 4 SDKs from 12.x. I can't reproduce it with any.

**Comment by Gcenx** [comment] 2021-03-22 17:22
Guess the OP has a corrupted Command Line Tools installation then I’ve seen similar issues opened for this with brew.

As you’ve personally verified it’s not an issue maybe it’s safe to close the issue as invalid.

**Closed** 2021-03-22 17:46 UTC
